version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - pwd
      - npm install -g typescript
      - npm install next
      - npm install
  build:
    commands:
      - pwd
      - npm run build
  post_build:
    commands:
      - echo $CODEBUILD_SRC_DIR

artifacts:
  files:
    - '**/*'

