version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - pwd
      - echo Installing dependencies now
      - npm install -g typescript
      - npm install next
      - npm install
      - echo Listing all files in current directory now
      - ls -la
  build:
    commands:
      - pwd
      - npm run build
      - echo Listing build files now
      - ls -la

artifacts:
  files:
    - '**/*'
  discard-paths: no