version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g npm-install-peers
      - npm install -g typescript
      - npm install next
      - npm install
      - npm-install-peers
  build:
    commands:
      - npm run build

artifacts:
  files:
    - package.json
    - package-lock.json
    - 'build/**/*'
  discard-paths: yes
