version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.15.1
    commands:
      - npm install -g typescript
      - npm install next
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - package.json
    - package-lock.json
    - 'build/**/*'
  discard-paths: yes
