version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript
      - npm install
  pre_build:
    commands:
      -echo Nothing to do in the pre_build phase...
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - package.json
    - package-lock.json
    - 'build/**/*'
  discard-paths: yes
