version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript
      - npm install next
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo $CODEBUILD_SRC_DIR

artifacts:
  files:
    - package.json
    - package-lock.json
    - 'build/**/*'
  discard-paths: yes
